FROM bensuperpc/tinycore:12.0-x86_64
LABEL maintainer "Ali Mosajjal <hi@n0p.me>"

RUN tce-load -wic python3.9 expat2 libffi
RUN sudo pip3 install --upgrade --no-cache-dir pip
RUN sudo pip3 install --no-cache-dir pproxy pycryptodome asyncssh aioquic pvpn
RUN sudo pip3 install --no-cache-dir https://files.pythonhosted.org/packages/ab/03/ed3a0d08c9d307e8babdbed7fc6c54b273602adb3fa41748b6c1785108b3/uvloop-0.17.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
USER root

ENTRYPOINT ["pproxy"]
